[project]
name = "pandas-exercises"
version = "0.1.0"
description = "pandas exercises, converted to uv"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.6",
    "numpy>=2.3.2",
    "pandas>=2.3.2",
    "seaborn>=0.13.2",
]
